# Generated by Django 3.2.5 on 2021-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_task_preffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
