# Generated by Django 3.2.5 on 2021-07-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_theme_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='number',
            new_name='order',
        ),
    ]
