# Generated by Django 3.2.5 on 2021-07-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210712_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['preffix', 'name']},
        ),
        migrations.AddField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='catalog.theme'),
        ),
        migrations.AlterField(
            model_name='task',
            name='preffix',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='', max_length=2),
        ),
    ]
