# Generated by Django 3.2.5 on 2021-07-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210712_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='catalog.theme'),
        ),
    ]
