# Generated by Django 3.2.5 on 2021-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_task_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='theme_id',
            field=models.CharField(default='', max_length=75),
        ),
    ]
