# Generated by Django 3.2.5 on 2021-07-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_task_theme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='defficult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='examples',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='input_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='memory',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='task',
            name='output_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.FloatField(default=0.5),
        ),
    ]
