# Generated by Django 3.2.5 on 2021-07-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210716_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='defficult',
            new_name='difficult',
        ),
    ]
