# Generated by Django 3.2.5 on 2021-07-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_rename_defficult_task_difficult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='theme_id',
        ),
    ]
